import { toMonthKey } from "@/lib/utils";
import type { DemoDatabase } from "@/lib/types";

const currentMonth = toMonthKey(new Date("2026-03-24T00:00:00.000Z"));
const previousMonth = "2026-02";

export const demoDatabaseSeed: DemoDatabase = {
  profiles: [
    {
      id: "user-sam",
      fullName: "Samira Khan",
      email: "player@gooddrive.club",
      role: "subscriber",
      selectedCharityId: "charity-first-swing",
      charityTier: 20,
      countryCode: "IN",
      currencyCode: "INR",
      createdAt: "2026-01-10T09:15:00.000Z",
    },
    {
      id: "user-owen",
      fullName: "Owen Bailey",
      email: "owen@gooddrive.club",
      role: "subscriber",
      selectedCharityId: "charity-blue-horizon",
      charityTier: 15,
      countryCode: "GB",
      currencyCode: "INR",
      createdAt: "2026-01-12T09:15:00.000Z",
    },
    {
      id: "user-meera",
      fullName: "Meera Nair",
      email: "meera@gooddrive.club",
      role: "subscriber",
      selectedCharityId: "charity-healing-greens",
      charityTier: 10,
      countryCode: "IN",
      currencyCode: "INR",
      createdAt: "2026-01-14T09:15:00.000Z",
    },
    {
      id: "admin-ava",
      fullName: "Ava Hart",
      email: "admin@gooddrive.club",
      role: "admin",
      selectedCharityId: "charity-first-swing",
      charityTier: 10,
      countryCode: "IN",
      currencyCode: "INR",
      createdAt: "2026-01-05T09:15:00.000Z",
    },
  ],
  demoAccounts: [
    { userId: "user-sam", password: "Player@2026" },
    { userId: "user-owen", password: "Player@2026" },
    { userId: "user-meera", password: "Player@2026" },
    { userId: "admin-ava", password: "Admin@2026" },
  ],
  plans: [
    {
      id: "plan-monthly",
      name: "Momentum Monthly",
      cadence: "monthly",
      baseAmountCents: 4900,
      stripeLookupKey: "good_drive_monthly",
      prizePoolBaseCents: 1800,
      baseCharityPercent: 10,
      enabledTiers: [10, 15, 20, 25, 30],
    },
    {
      id: "plan-yearly",
      name: "Impact Annual",
      cadence: "yearly",
      baseAmountCents: 49900,
      yearlySavingsLabel: "Save 15%",
      stripeLookupKey: "good_drive_yearly",
      prizePoolBaseCents: 21600,
      baseCharityPercent: 10,
      enabledTiers: [10, 15, 20, 25, 30],
    },
  ],
  subscriptions: [
    {
      id: "sub-sam",
      userId: "user-sam",
      planId: "plan-monthly",
      cadence: "monthly",
      status: "active",
      stripeCustomerId: "cus_demo_sam",
      stripeSubscriptionId: "sub_demo_sam",
      stripePriceId: "price_demo_monthly_20",
      currentPeriodStart: "2026-03-01T00:00:00.000Z",
      currentPeriodEnd: "2026-04-01T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      latestInvoiceStatus: "paid",
      updatedAt: "2026-03-01T00:00:00.000Z",
    },
    {
      id: "sub-owen",
      userId: "user-owen",
      planId: "plan-yearly",
      cadence: "yearly",
      status: "active",
      stripeCustomerId: "cus_demo_owen",
      stripeSubscriptionId: "sub_demo_owen",
      stripePriceId: "price_demo_yearly_15",
      currentPeriodStart: "2026-01-12T00:00:00.000Z",
      currentPeriodEnd: "2027-01-12T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      latestInvoiceStatus: "paid",
      updatedAt: "2026-01-12T00:00:00.000Z",
    },
    {
      id: "sub-meera",
      userId: "user-meera",
      planId: "plan-monthly",
      cadence: "monthly",
      status: "past_due",
      stripeCustomerId: "cus_demo_meera",
      stripeSubscriptionId: "sub_demo_meera",
      stripePriceId: "price_demo_monthly_10",
      currentPeriodStart: "2026-02-14T00:00:00.000Z",
      currentPeriodEnd: "2026-03-14T00:00:00.000Z",
      cancelAtPeriodEnd: false,
      latestInvoiceStatus: "open",
      updatedAt: "2026-03-14T00:00:00.000Z",
    },
  ],
  charities: [
    {
      id: "charity-first-swing",
      slug: "first-swing-futures",
      name: "First Swing Futures",
      category: "Youth Access",
      impactTag: "Open fair access to sport",
      description:
        "First Swing Futures funds coaching bursaries, travel grants, and safe beginner access for girls entering junior golf.",
      mission:
        "Create pathways into golf for children who normally never get onto a course, with local mentors and year-round support.",
      featured: true,
      images: ["/globe.svg", "/window.svg"],
      upcomingEvents: [
        {
          id: "event-1",
          charityId: "charity-first-swing",
          title: "Community short-game clinic",
          date: "2026-04-16T10:00:00.000Z",
          location: "Bengaluru",
          summary: "A free junior session led by volunteer coaches and adaptive-play mentors.",
        },
      ],
      totalRaisedCents: 182400,
      active: true,
    },
    {
      id: "charity-blue-horizon",
      slug: "blue-horizon-water-fund",
      name: "Blue Horizon Water Fund",
      category: "Clean Water",
      impactTag: "Every subscription extends a water line",
      description:
        "Blue Horizon builds small-scale water systems for drought-hit schools and rural sports programs.",
      mission:
        "Help communities keep children in school and sport by reducing time lost to unsafe water access.",
      featured: false,
      images: ["/file.svg", "/window.svg"],
      upcomingEvents: [
        {
          id: "event-2",
          charityId: "charity-blue-horizon",
          title: "Monsoon-proofing volunteer day",
          date: "2026-05-03T10:00:00.000Z",
          location: "Pune",
          summary: "Support field teams preparing filtration kits ahead of summer pressure peaks.",
        },
      ],
      totalRaisedCents: 146200,
      active: true,
    },
    {
      id: "charity-healing-greens",
      slug: "healing-greens-recovery-trust",
      name: "Healing Greens Recovery Trust",
      category: "Mental Health",
      impactTag: "Recovery spaces through movement",
      description:
        "Healing Greens creates trauma-aware outdoor recovery programs for young adults rebuilding confidence after crisis care.",
      mission:
        "Use movement, coaching, and calm outdoor environments to support recovery and social reconnection.",
      featured: false,
      images: ["/next.svg", "/globe.svg"],
      upcomingEvents: [
        {
          id: "event-3",
          charityId: "charity-healing-greens",
          title: "Mindful golf morning",
          date: "2026-04-28T08:00:00.000Z",
          location: "Hyderabad",
          summary: "A low-pressure community day focused on confidence, movement, and conversation.",
        },
      ],
      totalRaisedCents: 98400,
      active: true,
    },
  ],
  scoreEntries: [
    { id: "score-s1", userId: "user-sam", score: 12, playedAt: "2026-03-20", createdAt: "2026-03-20T08:00:00.000Z" },
    { id: "score-s2", userId: "user-sam", score: 18, playedAt: "2026-03-16", createdAt: "2026-03-16T08:00:00.000Z" },
    { id: "score-s3", userId: "user-sam", score: 23, playedAt: "2026-03-13", createdAt: "2026-03-13T08:00:00.000Z" },
    { id: "score-s4", userId: "user-sam", score: 33, playedAt: "2026-03-08", createdAt: "2026-03-08T08:00:00.000Z" },
    { id: "score-s5", userId: "user-sam", score: 41, playedAt: "2026-03-01", createdAt: "2026-03-01T08:00:00.000Z" },
    { id: "score-o1", userId: "user-owen", score: 8, playedAt: "2026-03-19", createdAt: "2026-03-19T08:00:00.000Z" },
    { id: "score-o2", userId: "user-owen", score: 18, playedAt: "2026-03-15", createdAt: "2026-03-15T08:00:00.000Z" },
    { id: "score-o3", userId: "user-owen", score: 23, playedAt: "2026-03-12", createdAt: "2026-03-12T08:00:00.000Z" },
    { id: "score-o4", userId: "user-owen", score: 31, playedAt: "2026-03-09", createdAt: "2026-03-09T08:00:00.000Z" },
    { id: "score-o5", userId: "user-owen", score: 44, playedAt: "2026-03-04", createdAt: "2026-03-04T08:00:00.000Z" },
    { id: "score-m1", userId: "user-meera", score: 7, playedAt: "2026-03-02", createdAt: "2026-03-02T08:00:00.000Z" },
    { id: "score-m2", userId: "user-meera", score: 14, playedAt: "2026-02-26", createdAt: "2026-02-26T08:00:00.000Z" },
    { id: "score-m3", userId: "user-meera", score: 19, playedAt: "2026-02-20", createdAt: "2026-02-20T08:00:00.000Z" },
    { id: "score-m4", userId: "user-meera", score: 29, playedAt: "2026-02-15", createdAt: "2026-02-15T08:00:00.000Z" },
    { id: "score-m5", userId: "user-meera", score: 37, playedAt: "2026-02-10", createdAt: "2026-02-10T08:00:00.000Z" },
  ],
  monthlyDraws: [
    {
      id: "draw-feb",
      monthKey: previousMonth,
      drawMode: "algorithmic",
      frequencyBias: "most_frequent",
      numbers: [12, 18, 23, 31, 44],
      publishedAt: "2026-02-28T12:00:00.000Z",
      prizePoolCents: 13400,
      rolloverFromPreviousCents: 0,
      fiveMatchPoolCents: 5360,
      fourMatchPoolCents: 4690,
      threeMatchPoolCents: 3350,
      charityTotalCents: 8720,
      simulationOnly: false,
    },
  ],
  drawResults: [
    {
      id: "result-feb-owen",
      drawId: "draw-feb",
      userId: "user-owen",
      matchedCount: 4,
      tier: "four_match",
      prizeCents: 4690,
      numbersMatched: [18, 23, 31, 44],
      claimStatus: "paid",
    },
    {
      id: "result-feb-sam",
      drawId: "draw-feb",
      userId: "user-sam",
      matchedCount: 3,
      tier: "three_match",
      prizeCents: 3350,
      numbersMatched: [12, 18, 23],
      claimStatus: "approved",
    },
  ],
  winnerClaims: [
    {
      id: "claim-feb-owen",
      drawResultId: "result-feb-owen",
      userId: "user-owen",
      proofUrl: "demo://owen-proof.png",
      status: "paid",
      notes: "Bank transfer completed and proof checked.",
      createdAt: "2026-03-01T09:00:00.000Z",
      reviewedAt: "2026-03-02T11:00:00.000Z",
    },
    {
      id: "claim-feb-sam",
      drawResultId: "result-feb-sam",
      userId: "user-sam",
      proofUrl: "demo://sam-proof.png",
      status: "approved",
      notes: "Ready for payout batch.",
      createdAt: "2026-03-01T12:00:00.000Z",
      reviewedAt: "2026-03-02T11:30:00.000Z",
    },
  ],
  charityLedger: [
    {
      id: "ledger-1",
      userId: "user-sam",
      charityId: "charity-first-swing",
      amountCents: 980,
      source: "subscription",
      recordedAt: "2026-03-01T09:00:00.000Z",
    },
    {
      id: "ledger-2",
      userId: "user-owen",
      charityId: "charity-blue-horizon",
      amountCents: 7485,
      source: "subscription",
      recordedAt: "2026-01-12T09:00:00.000Z",
    },
    {
      id: "ledger-3",
      userId: "user-sam",
      charityId: "charity-first-swing",
      amountCents: 2500,
      source: "donation",
      recordedAt: "2026-03-10T09:00:00.000Z",
    },
  ],
  donationLedger: [
    {
      id: "donation-1",
      userId: "user-sam",
      charityId: "charity-first-swing",
      amountCents: 2500,
      recordedAt: "2026-03-10T09:00:00.000Z",
    },
  ],
  payoutLedger: [
    {
      id: "payout-1",
      claimId: "claim-feb-owen",
      userId: "user-owen",
      amountCents: 4690,
      status: "paid",
      recordedAt: "2026-03-02T14:00:00.000Z",
    },
  ],
  auditLogs: [
    {
      id: "audit-1",
      actorId: "admin-ava",
      action: "draw.publish",
      targetType: "monthly_draw",
      targetId: "draw-feb",
      createdAt: "2026-02-28T12:01:00.000Z",
      summary: "Published February draw using algorithmic most-frequent mode.",
    },
  ],
  organizations: [{ id: "org-demo", name: "Digital Heroes Pilot", slug: "digital-heroes-pilot", active: true }],
  campaigns: [{ id: "campaign-demo", name: "Summer Impact Drive", slug: "summer-impact-drive", active: false }],
};

export const seededCurrentMonth = currentMonth;
